alias :wq='echo "On est pas dans Vim"'
alias :x='echo "On est pas dans Vim"'
alias deja='dpkg -l | grep -i ii | grep'
alias dir='ls --color=auto --format=vertical'
alias ds='dig +noauthority +noadditional +noqr +nostats +noidentify +nocmd +noquestion +nocomments'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias h='history'
alias head='head -n $((${LINES:-`tput lines 2>/dev/null||echo -n 12`} - 2))'
alias hosts='sudo vim /etc/hosts'
alias hy='history | grep -vE -e "[0-9]{1,4}  hy |history" | grep -iE -e '
alias i='sudo apt-get install'
alias idn_d='idn -d --quiet'
alias idn_e='idn --quiet'
alias ignoreca='svn propset svn:ignore file .'
alias l='ls -CF'
alias l.='ls -d .* --color=tty'
alias la='ls -A'
alias ll='ls -l'
alias ls='ls --color=auto'
alias minify='java -jar $HOME/bin/yuicompressor-2.4.2.jar'
alias my='mysql -u root -p'
alias nameprep='idn --quiet --stringprep'
alias nouveau='find . -print | xargs ls --color=none --sort=time -lgoh 2> /dev/null | grep -v "~"'
alias r='sudo apt-get remove'
alias s='apt-cache search'
#alias ubuntubuntu='sudo aptitude update;sudo aptitude safe-upgrade;sudo aptitude dist-upgrade'
alias vdir='ls --color=auto --format=long'
alias vide='echo -n "" >'
